In [58]:
import numpy as np
np.set_printoptions(suppress=True, threshold=np.inf)
import pandas as pd
pd.set_option('display.float_format',lambda x : '%.2f' % x)
import pde

class Diffusion_Model():
    def __init__(self, diffusivity=1, x_range = 10, y_range = 10,\
                 initial_field = np.zeros((10, 10)), R_field = np.zeros((10, 10))):
        self.diffusivity = diffusivity
        self.x_range = x_range
        self.y_range = y_range
        self.grid = pde.UnitGrid([x_range, y_range])
        self.R_field = pde.ScalarField(grid = self.grid, data = R_field)
        self.initial_field = pde.ScalarField(grid = self.grid, data = initial_field)
        self.PHY_PDE = DiffusionPDE_withR(diffusivity=diffusivity, R = self.R_field)
        
    def solve(self, t):
        return self.PHY_PDE.solve(self.initial_field, t_range = t).data

class DiffusionPDE_withR(pde.PDEBase):
    def __init__(self, diffusivity=1, bc="auto_periodic_neumann", bc_laplace="auto_periodic_neumann", R = 0):
        """ initialize the class with a diffusivity and boundary conditions
        for the actual field and its second derivative """
        self.diffusivity = diffusivity
        self.bc = bc
        self.bc_laplace = bc_laplace
        self.R = R
        
    def evolution_rate(self, state, t=0):
        """ numpy implementation of the evolution equation """
        state_lapacian = state.laplace(bc=self.bc)
        state_gradient = state.gradient(bc=self.bc)
        return (self.diffusivity * state_lapacian
                + self.R - state)

""" Example """
diffusivity_K = 10 # diffusivity

grid_x = grid_y = 10 # x,y coordinate range

initial_field_test = 10 * np.ones((grid_x, grid_y))\
                    + np.random.random((grid_x, grid_y))# randomly initialize "initial_field" map matrix around 10

R_test = np.zeros((grid_x, grid_y))# initialize pollution resource map matrix
R_test[7][2] = 1000 # a pollution resource in [7][2]

model_test = Diffusion_Model(diffusivity = diffusivity_K, x_range = grid_x, y_range = grid_y,\
                 initial_field = initial_field_test, R_field = R_test) # build model

In [59]:
model_test.solve(1) # model output at t = 1

  0%|          | 0/1.0 [00:00<?, ?it/s]

array([[ 5.39303775,  5.34334435,  5.23681078,  5.07146001,  4.86563568,
         4.64800824,  4.4490441 ,  4.28853045,  4.17857747,  4.12290008],
       [ 5.86084118,  5.80541073,  5.67221854,  5.45101765,  5.16660371,
         4.87045655,  4.60232915,  4.39221709,  4.24933866,  4.17848852],
       [ 6.87849032,  6.82226175,  6.64509373,  6.28998568,  5.82352961,
         5.34091082,  4.92285767,  4.60177264,  4.39195518,  4.28817259],
       [ 8.6018699 ,  8.59591508,  8.38554289,  7.77302601,  6.93649884,
         6.1113209 ,  5.42306045,  4.92232335,  4.60150451,  4.4481069 ],
       [11.23059922, 11.45428087, 11.36901559, 10.21119855,  8.65514098,
         7.21945567,  6.1104856 ,  5.33948357,  4.86868814,  4.64607638],
       [14.88430322, 15.88061982, 16.63351331, 14.10834481, 11.09052525,
         8.65408935,  6.93453338,  5.82088636,  5.16349167,  4.86230689],
       [19.25167386, 22.33467343, 27.00687894, 20.01003811, 14.10724705,
        10.20897107,  7.76978462,  6.28588224

In [60]:
model_test.solve(10) # model output at t = 10

  0%|          | 0/10.0 [00:00<?, ?it/s]

array([[ 4.86244375,  4.7517667 ,  4.52908281,  4.20372336,  3.80946762,
         3.39351443,  3.00569077,  2.68444465,  2.45764744,  2.3405383 ],
       [ 5.45919622,  5.33943174,  5.08391088,  4.69393921,  4.21105708,
         3.70578658,  3.23873059,  2.85919145,  2.59323806,  2.45764744],
       [ 6.72211431,  6.59539011,  6.28376533,  5.74370175,  5.05919279,
         4.34736618,  3.7108798 ,  3.20408264,  2.85919145,  2.68444465],
       [ 8.78321229,  8.69797255,  8.33702693,  7.51656933,  6.43580575,
         5.35309731,  4.42013381,  3.7108798 ,  3.23873059,  3.00569077],
       [11.80881845, 11.94330041, 11.68779266, 10.29598968,  8.46393657,
         6.73839631,  5.35309731,  4.34736618,  3.70578658,  3.39351443],
       [15.87976977, 16.77600021, 17.33887325, 14.55125154, 11.22530081,
         8.46393657,  6.43580575,  5.05919278,  4.21105708,  3.80946762],
       [20.64351785, 23.61660075, 28.07909107, 20.79397063, 14.55125154,
        10.29598968,  7.51656933,  5.74370175

In [61]:
model_test.solve(100) # model output at t = 100

  0%|          | 0/100.0 [00:00<?, ?it/s]

array([[ 4.86243463,  4.75170521,  4.52912094,  4.20362437,  3.80952981,
         3.39340713,  3.00574466,  2.68436141,  2.45766382,  2.34050231],
       [ 5.45913473,  5.33952225,  5.08371227,  4.69413854,  4.21078859,
         3.70600997,  3.23848616,  2.85934496,  2.59310245,  2.45766382],
       [ 6.72215245,  6.5951915 ,  6.28401704,  5.74333365,  5.0595533 ,
         4.34696056,  3.71120281,  3.20378584,  2.85934496,  2.68436141],
       [ 8.78311331,  8.69817189,  8.33665883,  7.51698223,  6.43530052,
         5.35355745,  4.41967582,  3.71120281,  3.23848616,  3.00574466],
       [11.80888068, 11.94303195, 11.6881532 , 10.29548446,  8.4644491 ,
         6.73783871,  5.35355745,  4.34696056,  3.70600997,  3.39340713],
       [15.87966251, 16.77622364, 17.33846767, 14.5517117 , 11.22474322,
         8.4644491 ,  6.43530052,  5.0595533 ,  4.21078859,  3.80952981],
       [20.64357179, 23.61635637, 28.07941413, 20.79351268, 14.5517117 ,
        10.29548446,  7.51698223,  5.74333365